language: node_js
node_js:
  - "9"
cache:
  directories:
  - node_modules
script:
  - npm run test:unit
  - npm run build
deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  keep-history: true
  local_dir: dist
  on:
    branch: master
